# config/chewy.yml
# separate environment configs
test:
  host: 'https://cherry-813679676.us-east-1.bonsaisearch.net/'
  prefix: 'test'
development:
  host: 'https://cherry-813679676.us-east-1.bonsaisearch.net/'