# config/chewy.yml
# separate environment configs
test:
  host: 'http://paas:d343a38b7f81439a2299c127edd732d2@thorin-us-east-1.searchly.com
'
  prefix: 'test'
development:
  host: 'http://paas:d343a38b7f81439a2299c127edd732d2@thorin-us-east-1.searchly.com
'